# Generated by Django 2.1.7 on 2021-11-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50, null=True)),
                ('microcip', models.CharField(max_length=30, null=True, verbose_name='Cod microcip')),
                ('specia', models.CharField(max_length=50, null=True)),
                ('rasa', models.CharField(max_length=50, null=True)),
                ('varstaluni', models.IntegerField(null=True, verbose_name='Varsta (luni)')),
                ('varstaani', models.IntegerField(null=True, verbose_name='Varsta (ani)')),
                ('gender', models.CharField(max_length=10, verbose_name='Sex')),
            ],
            options={
                'verbose_name_plural': 'Animale',
            },
        ),
        migrations.CreateModel(
            name='Proprietar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=40, null=True)),
                ('adresa', models.CharField(max_length=50, null=True)),
                ('telefon', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proprietari',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='proprietar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Proprietar'),
        ),
    ]
