# Generated by Django 2.1.7 on 2021-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='alimentatie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='altemodificari',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='anamneza',
            field=models.TextField(max_length=500, null=True, verbose_name='Anamneză'),
        ),
        migrations.AddField(
            model_name='animal',
            name='antecedente',
            field=models.TextField(max_length=300, null=True, verbose_name='Antecedente'),
        ),
        migrations.AddField(
            model_name='animal',
            name='atitudine',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='castrat',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='conformatie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='constitutie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='culoare',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='frecventapulsului',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='frecventarespiratorie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='greutate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='limfonoduriexplorabile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='limfonoduriexplorabiletextarea',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='mediudeviata',
            field=models.CharField(max_length=30, null=True, verbose_name='Mediu de viata'),
        ),
        migrations.AddField(
            model_name='animal',
            name='mucoaseaferente',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='parul',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='parulmodificat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='pielea',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='scorclinic',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperament',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='trc',
            field=models.FloatField(blank=True, null=True, verbose_name='TRC'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccinarideparazitari',
            field=models.CharField(max_length=30, null=True, verbose_name='Vaccinari si deparazitari'),
        ),
    ]
